language: cpp

compiler:  
    - gcc

before_script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libopencv-dev
    - sudo apt-get install libgoogle-glog-dev
    - mkdir build
    - cd build
    - cmake ..

script: make 
